server:
  endpoints:
    authz:
      web:
        implementation: ForwardAuth
        authn_strategies:
          - name: CookieSession
      basic:
        implementation: ForwardAuth
        authn_strategies:
          - name: HeaderAuthorization
            schemes: [ Basic ]

session:
  cookies:
    - domain: '{{ env "DOMAIN" }}'
      authelia_url: '{{ env "PORTAL_URL" }}'
