#!/bin/bash

set -eo pipefail

# (Re-)initialize managed configs
echo "[  •  ] Configuring syncthing..."
/syncthing-reset

# Start syncthing for normal operations
echo "[  •  ] Configuration done, restarting..."
exec syncthing serve
